services:
  web:
    build: .
    restart: always
    networks:
      - dokploy-network
    volumes:
      - app_data:/app/prisma
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DATABASE_URL=file:./dev.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grandtransfer-web.rule=Host(`межгород.com`) || Host(`www.межгород.com`)"
      - "traefik.http.services.grandtransfer-web.loadbalancer.server.port=3000"

volumes:
  app_data:


networks:
  dokploy-network:
    external: true
