services:
  web:
    build: .
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - app_data:/app/prisma
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DATABASE_URL=file:./dev.db

volumes:
  app_data:
