version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - app_data:/app/prisma
    environment:
      - DATABASE_URL=file:./dev.db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site-router.rule=Host(`xn--c1acbe2apap.com`) || Host(`www.xn--c1acbe2apap.com`)"
      - "traefik.http.services.site-router.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"

  bot:
    build: .
    command: npm run bot
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - app_data:/app/prisma
    environment:
      - DATABASE_URL=file:./dev.db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

networks:
  dokploy-network:
    external: true

volumes:
  app_data:
